chore: add deploy database

diff --git a/k8s/postgres.yml b/k8s/postgres.yml
--- a/k8s/postgres.yml
+++ b/k8s/postgres.yml
@@ -1,7 +1,8 @@
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
-  name: postgres-pvc
+  name: hotela
+  namespace: hotela
 spec:
   accessModes:
     - ReadWriteOnce
@@ -22,21 +23,44 @@ spec:
     metadata:
       labels:
         app: postgres
+      annotations:
+        vault.hashicorp.com/agent-inject: "true"
+        vault.hashicorp.com/role: "app-role"
+        vault.hashicorp.com/agent-inject-secret-hotela-env: 'kv/data/app/hotela'
+        vault.hashicorp.com/agent-inject-template-hotela-env: |
+          {{- with secret "kv/data/app/hotela" }}
+            export POSTGRES_USER="{{ .Data.data.DB_USER }}"
+            export POSTGRES_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
+          {{- end }}
     spec:
+      serviceAccountName: vault-auth
       containers:
         - name: postgres
           image: postgres:latest
+          command: [ "/bin/bash", "-c" ]
+          args:
+            - |
+              retries=0
+              max_retries=30
+              
+              echo "Waiting for secrets to be injected from Vault..."
+              
+              while [ ! -f /vault/secrets/hotela-env ]; do
+                if [ $retries -ge $max_retries ]; then
+                  echo "ERROR: Timed out after $(($max_retries * 2)) seconds waiting for Vault secret file."
+                  exit 1
+                fi
+                retries=$((retries + 1))
+                echo "Waiting... attempt ${retries}/${max_retries}"
+                sleep 2
+              done
+              
+              echo "Secrets found. Sourcing environment variables."
+              
+              source /vault/secrets/hotela-env
+              
+              exec docker-entrypoint.sh postgres
           env:
-            - name: POSTGRES_USER
-              valueFrom:
-                secretKeyRef:
-                  name: postgres-secret
-                  key: DB_USER
-            - name: POSTGRES_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: postgres-secret
-                  key: DB_PASSWORD
             - name: POSTGRES_DB
               value: hotela
             - name: TZ
@@ -49,16 +73,26 @@ spec:
       volumes:
         - name: postgres-storage
           persistentVolumeClaim:
-            claimName: postgres-pvc
+            claimName: hotela
+        - name: vault-token
+          projected:
+            sources:
+              - serviceAccountToken:
+                  path: token
+                  expirationSeconds: 3600
+                  audience: vault
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: postgres-service
 spec:
+  type: NodePort
   selector:
     app: postgres
   ports:
-    - protocol: TCP
+    - name: postgres
+      protocol: TCP
       port: 5432
       targetPort: 5432
+      nodePort: 30543
